"""Translation from a purely functional Python subset into Lean 4.

This module is the *modeling* step: it produces a Lean definition intended to
denote the same mathematical function as the Python source, plus one theorem
per `ensures` clause. The Lean kernel then certifies the theorems.

The translation gap lives here, so the rules are kept small, explicit, and
auditable:

  Python `int`        ->  Lean `Int` (both unbounded; no overflow gap)
  Python `bool`       ->  Lean `Bool`
  `+ - *` and unary - ->  the corresponding `Int` operations
  `// k`, `% k`       ->  Lean's `/`/`%` (Int.ediv/Int.emod under the
                          notation) when k is an integer literal >= 1:
                          floor and Euclidean division coincide for positive
                          divisors, and `omega` reasons about `/`/`%` by
                          literals. Reference.lean pins the notation's
                          semantics with kernel-checked examples.
  `//`, `%` otherwise ->  `Int.fdiv`/`Int.fmod` (floor-based, matching
                          Python's semantics on negative divisors; usually
                          beyond automation, so expect UNKNOWN)
  `if/elif/else`      ->  `if _ then _ else _` with a `Prop` condition
  assignments         ->  inlined by substitution (code is straight-line SSA
                          after inlining; no mutation survives translation)
  contracts           ->  `Prop`s: `==` becomes `=`, `and`/`or`/`not` become
                          `∧`/`∨`/`¬`, bool-valued terms `b` become `b = true`

  `min`/`max`/`abs`   ->  desugared to `if _ then _ else _` (usable in both
                          code and contracts)
  calls to module fns ->  inlined at the call site (sound for the acyclic
                          case; recursion is detected and refused)
  `for i in range(k)` ->  unrolled when the bounds are integer literals
                          (up to MAX_UNROLL iterations); `return` inside the
                          loop short-circuits later iterations exactly as in
                          Python, `break`/`continue` are refused

Anything outside the subset raises `UnsupportedError` — the verifier reports
the function as UNSUPPORTED rather than guessing at semantics. Notably `/`
(true division, which produces floats) and `**` are rejected, as are
unbounded loops, calls to functions outside the module, and container types.

Known modeling gap, by choice: Lean's division operators are total and
return 0 on a zero divisor, while Python raises ZeroDivisionError. For
literal divisors >= 1 the gap is unreachable; for variable divisors the
falsifier treats a raise on contract-legal inputs as a refutation, which
covers the gap whenever counterexample search is enabled (the default).
"""

from __future__ import annotations

import ast
from dataclasses import dataclass

from axiomprover.parser import SpecClause, TargetFunction

LEAN_TYPES = {"int": "Int", "bool": "Bool"}

# Lean 4 keywords / prelude names that would collide with generated binders.
_LEAN_RESERVED = {
    "if", "then", "else", "fun", "let", "in", "do", "match", "with", "by",
    "theorem", "def", "abbrev", "structure", "class", "instance", "where",
    "end", "open", "import", "from", "true", "false", "sorry", "result",
}


class UnsupportedError(Exception):
    """The construct is outside the verified subset. The message says which
    construct and where, so the user (or the generating model) can rewrite."""


# Bounded-loop unrolling budget. Fixed-iteration loops (checksums, fixed
# windows, unrolled kernels) fit comfortably; anything bigger deserves real
# invariant reasoning, which this translator does not pretend to have.
MAX_UNROLL = 64

# Call-inlining stack for cycle detection. The translator is synchronous and
# single-threaded; translate_function resets this on entry.
_inline_stack: list[str] = []


@dataclass
class LeanTheorem:
    name: str
    statement: str  # full `theorem ... := by` minus the tactic block
    clause_source: str  # original Python spec text, for reports


@dataclass
class LeanModule:
    """The generated Lean artifact for one Python function."""

    function_name: str
    definition: str
    theorems: list[LeanTheorem]
    proof_hint: str | None
    bool_params: list[str] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.bool_params is None:
            self.bool_params = []

    def render(self, tactics: list[str]) -> str:
        """Render a complete .lean file, pairing theorem i with tactics[i]."""
        assert len(tactics) == len(self.theorems)
        parts = [
            "-- Generated by AxiomProver. Audit the definition below against",
            "-- the Python source: it is the modeling step the kernel cannot",
            "-- check for you.",
            "set_option linter.unusedVariables false",
            "",
            self.definition,
            "",
        ]
        for theorem, tactic in zip(self.theorems, tactics):
            parts.append(f"{theorem.statement} := by\n  {tactic}")
            parts.append("")
        return "\n".join(parts)


def lean_name(python_name: str) -> str:
    return f"py_{python_name}" if python_name in _LEAN_RESERVED else python_name


def translate_function(fn: TargetFunction) -> LeanModule:
    _inline_stack.clear()
    _inline_stack.append(fn.name)
    body_expr = _compile_statements(fn.body, {p: lean_name(p) for p in fn.param_names}, fn)
    binders = " ".join(
        f"({lean_name(name)} : {LEAN_TYPES[ty]})" for name, ty in fn.params
    )
    definition = (
        f"def {lean_name(fn.name)} {binders} : {LEAN_TYPES[fn.return_type]} :=\n"
        f"  {body_expr}"
    )

    env = {p: lean_name(p) for p in fn.param_names}
    hyp_props = [
        _prop(clause.body, env, fn, bool_names=_bool_params(fn))
        for clause in fn.requires
    ]

    call = " ".join([lean_name(fn.name)] + [lean_name(p) for p in fn.param_names])
    theorems = []
    for i, clause in enumerate(fn.ensures, start=1):
        result_env = dict(env)
        result_env["result"] = f"({call})"
        bool_names = _bool_params(fn)
        if fn.return_type == "bool":
            bool_names = bool_names | {"result"}
        goal = _prop(clause.body, result_env, fn, bool_names=bool_names)
        hyp_binders = "".join(
            f" (_h{j} : {hyp})" for j, hyp in enumerate(hyp_props, start=1)
        )
        statement = (
            f"theorem {lean_name(fn.name)}_spec_{i} {binders}{hyp_binders} :\n"
            f"    {goal}"
        )
        theorems.append(
            LeanTheorem(
                name=f"{lean_name(fn.name)}_spec_{i}",
                statement=statement,
                clause_source=clause.source,
            )
        )

    return LeanModule(
        function_name=fn.name,
        definition=definition,
        theorems=theorems,
        proof_hint=fn.proof_hint,
        bool_params=[name for name, ty in fn.params if ty == "bool"],
    )


def _bool_params(fn: TargetFunction) -> set[str]:
    return {name for name, ty in fn.params if ty == "bool"}


# --------------------------------------------------------------------------
# Statements -> one expression
# --------------------------------------------------------------------------


def _compile_statements(
    stmts: list[ast.stmt], env: dict[str, str], fn: TargetFunction
) -> str:
    """Compile a statement list to a single Lean expression.

    `env` maps Python variable names to Lean expressions (parameters map to
    themselves; assigned variables map to their fully inlined definition).
    """
    if not stmts:
        raise UnsupportedError(
            f"{fn.name}: control flow can fall off the end of the function "
            f"without returning"
        )
    head, *rest = stmts

    if isinstance(head, ast.Return):
        if head.value is None:
            raise UnsupportedError(f"{fn.name}: bare 'return' is not supported")
        return _term(head.value, env, fn)

    if isinstance(head, ast.Assign):
        if len(head.targets) != 1 or not isinstance(head.targets[0], ast.Name):
            raise UnsupportedError(
                f"{fn.name}: only simple single-variable assignment is "
                f"supported (line {head.lineno})"
            )
        value = _term(head.value, env, fn)
        new_env = dict(env)
        new_env[head.targets[0].id] = value
        return _compile_statements(rest, new_env, fn)

    if isinstance(head, ast.AnnAssign):
        if not isinstance(head.target, ast.Name) or head.value is None:
            raise UnsupportedError(
                f"{fn.name}: unsupported annotated assignment (line {head.lineno})"
            )
        value = _term(head.value, env, fn)
        new_env = dict(env)
        new_env[head.target.id] = value
        return _compile_statements(rest, new_env, fn)

    if isinstance(head, ast.AugAssign):
        if not isinstance(head.target, ast.Name):
            raise UnsupportedError(
                f"{fn.name}: unsupported augmented assignment (line {head.lineno})"
            )
        desugared = ast.Assign(
            targets=[ast.Name(id=head.target.id, ctx=ast.Store())],
            value=ast.BinOp(
                left=ast.Name(id=head.target.id, ctx=ast.Load()),
                op=head.op,
                right=head.value,
            ),
        )
        ast.copy_location(desugared, head)
        ast.fix_missing_locations(desugared)
        return _compile_statements([desugared, *rest], env, fn)

    if isinstance(head, ast.If):
        cond = _prop(head.test, env, fn, bool_names=_bool_vars(env, fn))
        # Python semantics: a branch that returns ends the function; a branch
        # that falls through continues with `rest`. Inlining the continuation
        # into both arms is correct in every case (at the cost of duplication).
        then_expr = _compile_statements(list(head.body) + rest, env, fn)
        else_expr = _compile_statements(list(head.orelse) + rest, env, fn)
        return f"(if {cond} then {then_expr} else {else_expr})"

    if isinstance(head, ast.For):
        return _compile_statements(_unroll_for(head, fn) + rest, env, fn)

    if isinstance(head, ast.Pass):
        return _compile_statements(rest, env, fn)

    if isinstance(head, ast.Expr) and isinstance(head.value, ast.Constant):
        # Docstrings / stray literals.
        return _compile_statements(rest, env, fn)

    raise UnsupportedError(
        f"{fn.name}: statement {type(head).__name__} at line {head.lineno} is "
        f"outside the supported subset (no loops, calls, or containers yet)"
    )


def _unroll_for(loop: ast.For, fn: TargetFunction) -> list[ast.stmt]:
    """Expand `for i in range(<literals>)` into straight-line statements.

    Each iteration becomes `i = <value>` followed by a copy of the body, so
    the existing statement compiler handles everything downstream — including
    a `return` inside the loop, which short-circuits later iterations exactly
    as in Python. After the loop the variable stays bound to the last value
    (and stays unbound for an empty range), again matching Python.
    """
    if loop.orelse:
        raise UnsupportedError(
            f"{fn.name}: for/else is outside the subset (line {loop.lineno})"
        )
    if not isinstance(loop.target, ast.Name):
        raise UnsupportedError(
            f"{fn.name}: only a simple loop variable is supported "
            f"(line {loop.lineno})"
        )
    for node in ast.walk(loop):
        if isinstance(node, (ast.Break, ast.Continue)):
            raise UnsupportedError(
                f"{fn.name}: break/continue are outside the subset "
                f"(line {node.lineno})"
            )
    values = _range_literal_values(loop.iter, fn)
    if len(values) > MAX_UNROLL:
        raise UnsupportedError(
            f"{fn.name}: loop at line {loop.lineno} runs {len(values)} "
            f"iterations; the unrolling budget is {MAX_UNROLL}"
        )
    unrolled: list[ast.stmt] = []
    for value in values:
        assign = ast.Assign(
            targets=[ast.Name(id=loop.target.id, ctx=ast.Store())],
            value=ast.Constant(value=value),
        )
        ast.copy_location(assign, loop)
        ast.fix_missing_locations(assign)
        unrolled.append(assign)
        unrolled.extend(loop.body)
    return unrolled


def _range_literal_values(iter_node: ast.expr, fn: TargetFunction) -> list[int]:
    if not (
        isinstance(iter_node, ast.Call)
        and isinstance(iter_node.func, ast.Name)
        and iter_node.func.id == "range"
        and not iter_node.keywords
        and 1 <= len(iter_node.args) <= 3
    ):
        raise UnsupportedError(
            f"{fn.name}: loops are only supported over range(...) with "
            f"integer literal bounds (line {iter_node.lineno})"
        )
    bounds = []
    for arg in iter_node.args:
        value = _literal_int(arg)
        if value is None:
            raise UnsupportedError(
                f"{fn.name}: range bound {ast.unparse(arg)!r} is not an "
                f"integer literal; only fixed iteration counts can be "
                f"unrolled (line {arg.lineno})"
            )
        bounds.append(value)
    if len(bounds) == 3 and bounds[2] == 0:
        raise UnsupportedError(f"{fn.name}: range step of 0 (line {iter_node.lineno})")
    return list(range(*bounds))


def _literal_int(node: ast.expr) -> int | None:
    """The value of an integer literal, allowing a leading unary minus."""
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        inner = _literal_int(node.operand)
        return None if inner is None else -inner
    if (
        isinstance(node, ast.Constant)
        and isinstance(node.value, int)
        and not isinstance(node.value, bool)
    ):
        return node.value
    return None


def _bool_vars(env: dict[str, str], fn: TargetFunction) -> set[str]:
    # Conservative: only parameters carry reliable type information. Local
    # bool-typed assignments used in `if` conditions are handled through
    # `_term`'s bool handling when they are comparisons.
    return _bool_params(fn)


# --------------------------------------------------------------------------
# Expressions
# --------------------------------------------------------------------------

_BINOPS = {
    ast.Add: "+",
    ast.Sub: "-",
    ast.Mult: "*",
}

_CMPOPS = {
    ast.Eq: "=",
    ast.NotEq: "≠",
    ast.Lt: "<",
    ast.LtE: "≤",
    ast.Gt: ">",
    ast.GtE: "≥",
}


def _is_positive_literal(node: ast.expr) -> bool:
    """True for an integer literal >= 1 (bools excluded)."""
    return (
        isinstance(node, ast.Constant)
        and isinstance(node.value, int)
        and not isinstance(node.value, bool)
        and node.value >= 1
    )


def _term(node: ast.expr, env: dict[str, str], fn: TargetFunction) -> str:
    """Translate an expression in *value* position (Int or Bool)."""
    if isinstance(node, ast.Constant):
        if isinstance(node.value, bool):
            return "true" if node.value else "false"
        if isinstance(node.value, int):
            return str(node.value) if node.value >= 0 else f"({node.value})"
        raise UnsupportedError(
            f"{fn.name}: literal {node.value!r} of type "
            f"{type(node.value).__name__} is not in the Int/Bool subset"
        )

    if isinstance(node, ast.Name):
        if node.id not in env:
            raise UnsupportedError(
                f"{fn.name}: name '{node.id}' is not a parameter or previously "
                f"assigned local (line {node.lineno})"
            )
        return env[node.id]

    if isinstance(node, ast.BinOp):
        left = _term(node.left, env, fn)
        right = _term(node.right, env, fn)
        op_type = type(node.op)
        if op_type in _BINOPS:
            return f"({left} {_BINOPS[op_type]} {right})"
        # Lean's `/`/`%` notation on Int is Euclidean division, which agrees
        # with Python's floor division exactly when the divisor is positive
        # (Reference.lean pins this with kernel-checked examples). We emit
        # the notation, not raw Int.ediv/Int.emod: omega's frontend matches
        # the HDiv/HMod applications and misses the bare constants.
        if op_type is ast.FloorDiv:
            if _is_positive_literal(node.right):
                return f"({left} / {right})"
            return f"(Int.fdiv {left} {right})"
        if op_type is ast.Mod:
            if _is_positive_literal(node.right):
                return f"({left} % {right})"
            return f"(Int.fmod {left} {right})"
        if op_type is ast.Div:
            raise UnsupportedError(
                f"{fn.name}: '/' is float division and has no Int model; use "
                f"'//' (line {node.lineno})"
            )
        raise UnsupportedError(
            f"{fn.name}: operator {op_type.__name__} is outside the subset "
            f"(line {node.lineno})"
        )

    if isinstance(node, ast.UnaryOp):
        if isinstance(node.op, ast.USub):
            return f"(-{_term(node.operand, env, fn)})"
        if isinstance(node.op, ast.Not):
            return f"(!{_term(node.operand, env, fn)})"
        raise UnsupportedError(
            f"{fn.name}: unary {type(node.op).__name__} is outside the subset"
        )

    if isinstance(node, ast.Compare):
        # Bool-valued comparison: model as the decidable proposition.
        return f"(decide {_prop(node, env, fn, bool_names=set())})"

    if isinstance(node, ast.BoolOp):
        op = "&&" if isinstance(node.op, ast.And) else "||"
        parts = [_term(v, env, fn) for v in node.values]
        return "(" + f" {op} ".join(parts) + ")"

    if isinstance(node, ast.IfExp):
        cond = _prop(node.test, env, fn, bool_names=_bool_params(fn))
        then_expr = _term(node.body, env, fn)
        else_expr = _term(node.orelse, env, fn)
        return f"(if {cond} then {then_expr} else {else_expr})"

    if isinstance(node, ast.Call):
        return _call(node, env, fn)

    raise UnsupportedError(
        f"{fn.name}: expression {type(node).__name__} at line {node.lineno} "
        f"is outside the supported subset"
    )


def _call(node: ast.Call, env: dict[str, str], fn: TargetFunction) -> str:
    """Builtin desugaring (min/max/abs) and inlining of module functions."""
    if not isinstance(node.func, ast.Name) or node.keywords:
        raise UnsupportedError(
            f"{fn.name}: only plain positional calls to named functions are "
            f"supported (line {node.lineno})"
        )
    name = node.func.id
    if name in env:
        raise UnsupportedError(
            f"{fn.name}: calling {name!r} which is shadowed by a local "
            f"variable (line {node.lineno})"
        )
    args = [_term(arg, env, fn) for arg in node.args]

    # Builtins are desugared to `ite`, mirroring their Python definitions.
    # A module function of the same name deliberately takes precedence.
    if name not in fn.helpers:
        if name in ("min", "max") and len(args) >= 2:
            op = "≤" if name == "min" else "≥"
            acc = args[0]
            for nxt in args[1:]:
                acc = f"(if {acc} {op} {nxt} then {acc} else {nxt})"
            return acc
        if name == "abs" and len(args) == 1:
            x = args[0]
            return f"(if {x} < 0 then (-{x}) else {x})"
        raise UnsupportedError(
            f"{fn.name}: call to {name!r} at line {node.lineno} — not a "
            f"module function, and not a supported builtin (min/max/abs)"
        )

    return _inline(fn.helpers[name], args, node, fn)


def _inline(
    helper: ast.FunctionDef, args: list[str], call: ast.Call, fn: TargetFunction
) -> str:
    """Substitute translated argument expressions for the helper's parameters
    and compile its body in place. Sound because the subset is pure: argument
    expressions have no effects, so call-by-name equals call-by-value."""
    if helper.name in _inline_stack:
        cycle = " -> ".join([*_inline_stack, helper.name])
        raise UnsupportedError(
            f"{fn.name}: recursive call chain {cycle} (line {call.lineno}); "
            f"recursion is not yet in the verified subset"
        )
    params = helper.args
    if params.posonlyargs or params.kwonlyargs or params.vararg or params.kwarg or params.defaults:
        raise UnsupportedError(
            f"{fn.name}: callee {helper.name!r} must take only plain "
            f"positional parameters (line {call.lineno})"
        )
    if len(params.args) != len(args):
        raise UnsupportedError(
            f"{fn.name}: call to {helper.name!r} passes {len(args)} "
            f"argument(s), expected {len(params.args)} (line {call.lineno})"
        )
    callee_env = {p.arg: arg for p, arg in zip(params.args, args)}
    _inline_stack.append(helper.name)
    try:
        return _compile_statements(helper.body, callee_env, fn)
    finally:
        _inline_stack.pop()


def _prop(
    node: ast.expr,
    env: dict[str, str],
    fn: TargetFunction,
    bool_names: set[str],
) -> str:
    """Translate an expression in *proposition* position (contracts and `if`
    conditions). `bool_names` lists env entries of Bool type, which must be
    coerced via `= true` to live in Prop."""
    if isinstance(node, ast.Compare):
        left = _term(node.left, env, fn)
        conjuncts = []
        for op, comparator in zip(node.ops, node.comparators):
            op_type = type(op)
            if op_type not in _CMPOPS:
                raise UnsupportedError(
                    f"{fn.name}: comparison {op_type.__name__} is outside the "
                    f"subset (line {node.lineno})"
                )
            right = _term(comparator, env, fn)
            conjuncts.append(f"{left} {_CMPOPS[op_type]} {right}")
            left = right
        joined = " ∧ ".join(conjuncts)
        return f"({joined})"

    if isinstance(node, ast.BoolOp):
        op = " ∧ " if isinstance(node.op, ast.And) else " ∨ "
        parts = [_prop(v, env, fn, bool_names) for v in node.values]
        return "(" + op.join(parts) + ")"

    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
        return f"(¬ {_prop(node.operand, env, fn, bool_names)})"

    if isinstance(node, ast.Constant) and isinstance(node.value, bool):
        return "True" if node.value else "False"

    if isinstance(node, ast.Name) and node.id in bool_names:
        return f"({env[node.id]} = true)"

    # Fall back: a Bool-valued term used as a proposition.
    term = _term(node, env, fn)
    return f"({term} = true)"
