"""Translation from a purely functional Python subset into Lean 4.

This module is the *modeling* step: it produces a Lean definition intended to
denote the same mathematical function as the Python source, plus one theorem
per `ensures` clause. The Lean kernel then certifies the theorems.

The translation gap lives here, so the rules are kept small, explicit, and
auditable:

  Python `int`        ->  Lean `Int` (both unbounded; no overflow gap)
  Python `bool`       ->  Lean `Bool`
  `+ - *` and unary - ->  the corresponding `Int` operations
  `// k`, `% k`       ->  `Int.ediv`/`Int.emod` when k is an integer literal
                          >= 1 (floor and Euclidean division coincide for
                          positive divisors, and `omega` can reason about
                          ediv/emod by literals)
  `//`, `%` otherwise ->  `Int.fdiv`/`Int.fmod` (floor-based, matching
                          Python's semantics on negative divisors; usually
                          beyond automation, so expect UNKNOWN)
  `if/elif/else`      ->  `if _ then _ else _` with a `Prop` condition
  assignments         ->  inlined by substitution (code is straight-line SSA
                          after inlining; no mutation survives translation)
  contracts           ->  `Prop`s: `==` becomes `=`, `and`/`or`/`not` become
                          `∧`/`∨`/`¬`, bool-valued terms `b` become `b = true`

Anything outside the subset raises `UnsupportedError` — the verifier reports
the function as UNSUPPORTED rather than guessing at semantics. Notably `/`
(true division, which produces floats) and `**` are rejected, as are loops,
calls, and container types.

Known modeling gap, by choice: Lean's division operators are total and
return 0 on a zero divisor, while Python raises ZeroDivisionError. For
literal divisors >= 1 the gap is unreachable; for variable divisors the
falsifier treats a raise on contract-legal inputs as a refutation, which
covers the gap whenever counterexample search is enabled (the default).
"""

from __future__ import annotations

import ast
from dataclasses import dataclass

from axiomprover.parser import SpecClause, TargetFunction

LEAN_TYPES = {"int": "Int", "bool": "Bool"}

# Lean 4 keywords / prelude names that would collide with generated binders.
_LEAN_RESERVED = {
    "if", "then", "else", "fun", "let", "in", "do", "match", "with", "by",
    "theorem", "def", "abbrev", "structure", "class", "instance", "where",
    "end", "open", "import", "from", "true", "false", "sorry", "result",
}


class UnsupportedError(Exception):
    """The construct is outside the verified subset. The message says which
    construct and where, so the user (or the generating model) can rewrite."""


@dataclass
class LeanTheorem:
    name: str
    statement: str  # full `theorem ... := by` minus the tactic block
    clause_source: str  # original Python spec text, for reports


@dataclass
class LeanModule:
    """The generated Lean artifact for one Python function."""

    function_name: str
    definition: str
    theorems: list[LeanTheorem]
    proof_hint: str | None
    bool_params: list[str] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.bool_params is None:
            self.bool_params = []

    def render(self, tactics: list[str]) -> str:
        """Render a complete .lean file, pairing theorem i with tactics[i]."""
        assert len(tactics) == len(self.theorems)
        parts = [
            "-- Generated by AxiomProver. Audit the definition below against",
            "-- the Python source: it is the modeling step the kernel cannot",
            "-- check for you.",
            "set_option linter.unusedVariables false",
            "",
            self.definition,
            "",
        ]
        for theorem, tactic in zip(self.theorems, tactics):
            parts.append(f"{theorem.statement} := by\n  {tactic}")
            parts.append("")
        return "\n".join(parts)


def lean_name(python_name: str) -> str:
    return f"py_{python_name}" if python_name in _LEAN_RESERVED else python_name


def translate_function(fn: TargetFunction) -> LeanModule:
    body_expr = _compile_statements(fn.body, {p: lean_name(p) for p in fn.param_names}, fn)
    binders = " ".join(
        f"({lean_name(name)} : {LEAN_TYPES[ty]})" for name, ty in fn.params
    )
    definition = (
        f"def {lean_name(fn.name)} {binders} : {LEAN_TYPES[fn.return_type]} :=\n"
        f"  {body_expr}"
    )

    env = {p: lean_name(p) for p in fn.param_names}
    hyp_props = [
        _prop(clause.body, env, fn, bool_names=_bool_params(fn))
        for clause in fn.requires
    ]

    call = " ".join([lean_name(fn.name)] + [lean_name(p) for p in fn.param_names])
    theorems = []
    for i, clause in enumerate(fn.ensures, start=1):
        result_env = dict(env)
        result_env["result"] = f"({call})"
        bool_names = _bool_params(fn)
        if fn.return_type == "bool":
            bool_names = bool_names | {"result"}
        goal = _prop(clause.body, result_env, fn, bool_names=bool_names)
        hyp_binders = "".join(
            f" (_h{j} : {hyp})" for j, hyp in enumerate(hyp_props, start=1)
        )
        statement = (
            f"theorem {lean_name(fn.name)}_spec_{i} {binders}{hyp_binders} :\n"
            f"    {goal}"
        )
        theorems.append(
            LeanTheorem(
                name=f"{lean_name(fn.name)}_spec_{i}",
                statement=statement,
                clause_source=clause.source,
            )
        )

    return LeanModule(
        function_name=fn.name,
        definition=definition,
        theorems=theorems,
        proof_hint=fn.proof_hint,
        bool_params=[name for name, ty in fn.params if ty == "bool"],
    )


def _bool_params(fn: TargetFunction) -> set[str]:
    return {name for name, ty in fn.params if ty == "bool"}


# --------------------------------------------------------------------------
# Statements -> one expression
# --------------------------------------------------------------------------


def _compile_statements(
    stmts: list[ast.stmt], env: dict[str, str], fn: TargetFunction
) -> str:
    """Compile a statement list to a single Lean expression.

    `env` maps Python variable names to Lean expressions (parameters map to
    themselves; assigned variables map to their fully inlined definition).
    """
    if not stmts:
        raise UnsupportedError(
            f"{fn.name}: control flow can fall off the end of the function "
            f"without returning"
        )
    head, *rest = stmts

    if isinstance(head, ast.Return):
        if head.value is None:
            raise UnsupportedError(f"{fn.name}: bare 'return' is not supported")
        return _term(head.value, env, fn)

    if isinstance(head, ast.Assign):
        if len(head.targets) != 1 or not isinstance(head.targets[0], ast.Name):
            raise UnsupportedError(
                f"{fn.name}: only simple single-variable assignment is "
                f"supported (line {head.lineno})"
            )
        value = _term(head.value, env, fn)
        new_env = dict(env)
        new_env[head.targets[0].id] = value
        return _compile_statements(rest, new_env, fn)

    if isinstance(head, ast.AnnAssign):
        if not isinstance(head.target, ast.Name) or head.value is None:
            raise UnsupportedError(
                f"{fn.name}: unsupported annotated assignment (line {head.lineno})"
            )
        value = _term(head.value, env, fn)
        new_env = dict(env)
        new_env[head.target.id] = value
        return _compile_statements(rest, new_env, fn)

    if isinstance(head, ast.AugAssign):
        if not isinstance(head.target, ast.Name):
            raise UnsupportedError(
                f"{fn.name}: unsupported augmented assignment (line {head.lineno})"
            )
        desugared = ast.Assign(
            targets=[ast.Name(id=head.target.id, ctx=ast.Store())],
            value=ast.BinOp(
                left=ast.Name(id=head.target.id, ctx=ast.Load()),
                op=head.op,
                right=head.value,
            ),
        )
        ast.copy_location(desugared, head)
        ast.fix_missing_locations(desugared)
        return _compile_statements([desugared, *rest], env, fn)

    if isinstance(head, ast.If):
        cond = _prop(head.test, env, fn, bool_names=_bool_vars(env, fn))
        # Python semantics: a branch that returns ends the function; a branch
        # that falls through continues with `rest`. Inlining the continuation
        # into both arms is correct in every case (at the cost of duplication).
        then_expr = _compile_statements(list(head.body) + rest, env, fn)
        else_expr = _compile_statements(list(head.orelse) + rest, env, fn)
        return f"(if {cond} then {then_expr} else {else_expr})"

    if isinstance(head, ast.Pass):
        return _compile_statements(rest, env, fn)

    if isinstance(head, ast.Expr) and isinstance(head.value, ast.Constant):
        # Docstrings / stray literals.
        return _compile_statements(rest, env, fn)

    raise UnsupportedError(
        f"{fn.name}: statement {type(head).__name__} at line {head.lineno} is "
        f"outside the supported subset (no loops, calls, or containers yet)"
    )


def _bool_vars(env: dict[str, str], fn: TargetFunction) -> set[str]:
    # Conservative: only parameters carry reliable type information. Local
    # bool-typed assignments used in `if` conditions are handled through
    # `_term`'s bool handling when they are comparisons.
    return _bool_params(fn)


# --------------------------------------------------------------------------
# Expressions
# --------------------------------------------------------------------------

_BINOPS = {
    ast.Add: "+",
    ast.Sub: "-",
    ast.Mult: "*",
}

_CMPOPS = {
    ast.Eq: "=",
    ast.NotEq: "≠",
    ast.Lt: "<",
    ast.LtE: "≤",
    ast.Gt: ">",
    ast.GtE: "≥",
}


def _is_positive_literal(node: ast.expr) -> bool:
    """True for an integer literal >= 1 (bools excluded)."""
    return (
        isinstance(node, ast.Constant)
        and isinstance(node.value, int)
        and not isinstance(node.value, bool)
        and node.value >= 1
    )


def _term(node: ast.expr, env: dict[str, str], fn: TargetFunction) -> str:
    """Translate an expression in *value* position (Int or Bool)."""
    if isinstance(node, ast.Constant):
        if isinstance(node.value, bool):
            return "true" if node.value else "false"
        if isinstance(node.value, int):
            return str(node.value) if node.value >= 0 else f"({node.value})"
        raise UnsupportedError(
            f"{fn.name}: literal {node.value!r} of type "
            f"{type(node.value).__name__} is not in the Int/Bool subset"
        )

    if isinstance(node, ast.Name):
        if node.id not in env:
            raise UnsupportedError(
                f"{fn.name}: name '{node.id}' is not a parameter or previously "
                f"assigned local (line {node.lineno})"
            )
        return env[node.id]

    if isinstance(node, ast.BinOp):
        left = _term(node.left, env, fn)
        right = _term(node.right, env, fn)
        op_type = type(node.op)
        if op_type in _BINOPS:
            return f"({left} {_BINOPS[op_type]} {right})"
        if op_type is ast.FloorDiv:
            if _is_positive_literal(node.right):
                return f"(Int.ediv {left} {right})"
            return f"(Int.fdiv {left} {right})"
        if op_type is ast.Mod:
            if _is_positive_literal(node.right):
                return f"(Int.emod {left} {right})"
            return f"(Int.fmod {left} {right})"
        if op_type is ast.Div:
            raise UnsupportedError(
                f"{fn.name}: '/' is float division and has no Int model; use "
                f"'//' (line {node.lineno})"
            )
        raise UnsupportedError(
            f"{fn.name}: operator {op_type.__name__} is outside the subset "
            f"(line {node.lineno})"
        )

    if isinstance(node, ast.UnaryOp):
        if isinstance(node.op, ast.USub):
            return f"(-{_term(node.operand, env, fn)})"
        if isinstance(node.op, ast.Not):
            return f"(!{_term(node.operand, env, fn)})"
        raise UnsupportedError(
            f"{fn.name}: unary {type(node.op).__name__} is outside the subset"
        )

    if isinstance(node, ast.Compare):
        # Bool-valued comparison: model as the decidable proposition.
        return f"(decide {_prop(node, env, fn, bool_names=set())})"

    if isinstance(node, ast.BoolOp):
        op = "&&" if isinstance(node.op, ast.And) else "||"
        parts = [_term(v, env, fn) for v in node.values]
        return "(" + f" {op} ".join(parts) + ")"

    if isinstance(node, ast.IfExp):
        cond = _prop(node.test, env, fn, bool_names=_bool_params(fn))
        then_expr = _term(node.body, env, fn)
        else_expr = _term(node.orelse, env, fn)
        return f"(if {cond} then {then_expr} else {else_expr})"

    raise UnsupportedError(
        f"{fn.name}: expression {type(node).__name__} at line {node.lineno} "
        f"is outside the supported subset"
    )


def _prop(
    node: ast.expr,
    env: dict[str, str],
    fn: TargetFunction,
    bool_names: set[str],
) -> str:
    """Translate an expression in *proposition* position (contracts and `if`
    conditions). `bool_names` lists env entries of Bool type, which must be
    coerced via `= true` to live in Prop."""
    if isinstance(node, ast.Compare):
        left = _term(node.left, env, fn)
        conjuncts = []
        for op, comparator in zip(node.ops, node.comparators):
            op_type = type(op)
            if op_type not in _CMPOPS:
                raise UnsupportedError(
                    f"{fn.name}: comparison {op_type.__name__} is outside the "
                    f"subset (line {node.lineno})"
                )
            right = _term(comparator, env, fn)
            conjuncts.append(f"{left} {_CMPOPS[op_type]} {right}")
            left = right
        joined = " ∧ ".join(conjuncts)
        return f"({joined})"

    if isinstance(node, ast.BoolOp):
        op = " ∧ " if isinstance(node.op, ast.And) else " ∨ "
        parts = [_prop(v, env, fn, bool_names) for v in node.values]
        return "(" + op.join(parts) + ")"

    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
        return f"(¬ {_prop(node.operand, env, fn, bool_names)})"

    if isinstance(node, ast.Constant) and isinstance(node.value, bool):
        return "True" if node.value else "False"

    if isinstance(node, ast.Name) and node.id in bool_names:
        return f"({env[node.id]} = true)"

    # Fall back: a Bool-valued term used as a proposition.
    term = _term(node, env, fn)
    return f"({term} = true)"
